### ISSUE TITLE
Hey, Polymars would not be super happy about this

### ISSUE THREAD

**Issue by Ubuntufanboy** [Akshat-unt/Buckshot#3]
# Dude

This is not your code :sob: 

Why...

**Comment by Akshat-sin-official** [comment]
Hey!
Great catch hmm... am too a Polymars & Barji's follower, they're fun! 😄

TBH @ the time of their Python game challenge I was so excited that I downloaded the exe and code from their website & maybe forgot about the acknowledgment section... am sorry ! 😅 

I'll be adding the Acknowledgement soon hoping that'll close the issue...

Thanks again!
keep surfing bro...
😉
